# Generated by Django 2.1 on 2018-12-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181013_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/categories/images/no-img.jpg', upload_to='static/categories/images/'),
        ),
    ]
