# Generated by Django 2.1 on 2018-12-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Short description of the content', max_length=100, verbose_name='description'),
        ),
    ]
