SELECT TOP (1000) [Id]
      ,[Username]
      ,[PasswordHash]
      ,[PasswordSalt]
      ,[Gender]
      ,[DateOfBirth]
      ,[KnownAs]
      ,[Created]
      ,[LastActive]
      ,[Introduction]
      ,[LookingFor]
      ,[Interests]
      ,[City]
      ,[Country]
  FROM [dbo].[Users]